#!/bin/bash
#execute some stuff and then ask is you really want to push
./ci/codesniffer.sh
phpunit
read -p "You're about to push, are you sure you won't break the build? " -n 1 -r < /dev/tty
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    exit 0 # push will execute
fi
exit 1 # push will not execute

--------------------------------
#!/bin/bash
# If the following text is found anywhere in the source for HEAD, we will prevent pushing
dont_push_flag="DONT PUSH ME"

flag_found=`git grep --color "$dont_push_flag" HEAD`
if [ -n "$flag_found" ]
then
    # Display which commit the first occurence of the flag was found and exit failure
    commit=`git log --pretty=format:'%Cred%h%Creset' -S "$dont_push_flag" | tail -n1`
    echo "Found $flag_found, first occurence was in $commit, not pushing"
    exit 1
fi
exit 0
