Vagrant.configure(2) do |config|
	config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
	end
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "private_network", ip: "192.168.111.111"
    config.vm.network "public_network"
end
